version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./web

    ports:
      - "3002:3002"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "3000:3000"
